#ifndef DEFINES_H
#define DEFINES_H

#define str_0 "SYS:S/User-Startup"
#define str_1 "RAM:T/User-Startup"
#define str_2 "RAM:T/weather.json"
#define str_3 "SYS:Prefs/Env-Archive/Sys/Palette.prefs"
#define str_4 "SYS:Prefs/Env-Archive/AmiWeatherForecasts.prefs"
#define str_5 "SYS:Prefs/Time"
#define str_6 "SYS:C/sntp pool.ntp.org >NIL:"
#define str_7 "RAM:T/ip.txt"
#define str_8 "SYS:C/GetExtIP"
#define str_9 " > "
#define str_10 "RAM:T/mylocation.txt"
#define str_11 "ca, Catalan"
#define str_12 "da, Danish"
#define str_13 "de, German"
#define str_14 "en, English"
#define str_15 "eu, Basque"
#define str_16 "fi, Finnish"
#define str_17 "fr, French"
#define str_19 "it, Italian"
#define str_20 "no, Norwegian"
#define str_21 "nl, Dutch"
#define str_22 "pt, Portuguese"
#define str_23 "sv, Swedish"
#define str_24 "es, Spanish"
#define str_25 "tr, Turkish"
#define str_26 "Bar"
#define str_27 "Iconic"
#define str_28 "Digital"
#define str_149 "Invisible"
#define str_38 "AmiWeatherForecasts"
#define str_47 ""
#define str_49 "istanbul,tr"
#define str_50 "metric"
#define str_51 "e45eeea40d4a9754ef176588dd068f18"
#define str_52 "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec"
#define str_53 "Sun,Mon,Tue,Wed,Thu,Fri,Sat"
#define str_54 "1"
#define str_55 "SetEnv "
#define str_56 "="
#define str_57 " >NIL:"
#define str_58 " %s %d, %s %02d:%02d "
#define str_59 " %s "
#define str_60 "0"
#define str_61 " "
#define str_62 "["
#define str_63 "] "
#define str_64 "currenttemperature"
#define str_65 "weatherdescription"
#define str_66 "location"
#define str_67 "r"
#define str_68 "/"
#define str_69 "SYS:Utilities/MultiView "
#define str_70 ".guide"
#define str_71 "intuition.library"
#define str_72 "graphics.library"
#define str_73 "gadgets/checkbox.gadget"
#define str_74 "SYS:Prefs/Palette SAVE >NIL:"
#define str_75 "SYS:C/sntp"
#define str_76 "SYS:C/delete RAM:T/weather.json >NIL:"
#define str_81 "echo \"*N*NRun >NIL: %s ; %s\" >> %s >NIL:"
#define str_86 "X"
#define str_87 "-"
#define str_88 "|"
#define str_89 "%s"
#define str_90 ","
#define str_91 "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%d\n%d\n%d\n%d\n%d\n%d\n%d\n%d\n%d\n%d\n%d\n%d\n%s\n%s\n%s\n%s\n%s\n%d\n%d\n%d\n"
#define str_92 "imperial"
#define str_107 "           "
#define str_131 " CurrentTemperature "
#define str_132 " WeatherDescription "
#define str_133 " Location "
#define str_142 "http://ip-api.com/csv/%s"
#define str_143 "success"
#define str_144 "SYS:C/delete RAM:T/#?.txt >NIL:"
#define str_146 "copy %s to RAM:T/ QUIET >NIL:"
#define str_147 "SYS:C/delete "
#define str_150 "SYS:Utilities/espeak-m68020-60"
#define str_151 "$Location , $CurrentTemperature , $WeatherDescription"
#define str_152 "trigger"
#define str_153 "trigger=0"
#define str_154 "espeak-m68#?"
#define str_155 "SYS:Internet/AmiWF/AmiWeatherForecasts"
#define str_156 "             "

#define USERSTARTUP str_0
#define COPIEDUSERSTARTUP str_1
#define TRIGGER "trigger=1"
#define AMIGA "! Amiga"

#endif
