#define FONTWIDTH   17
#define FONTHEIGHT  23
#define FONTCOUNT   11

#define PANELWIDTH  107
#define PANELHEIGHT 46

/*
Colors:
'*': text
' ': background
'B': panel
'W': light
*/

char digitalPanel[PANELHEIGHT][PANELWIDTH] =
{
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "WBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "WBBB***B***B*BBB*B***BB***B***BBB**BB***B*BB*B***BB***BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "WBBBB*BB*BBB**B**B*BB*B*BBB*BB*BB**BBB*BB*BB*B*BB*B*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "WBBBB*BB**BB*B*B*B***BB**BB***BB*BB*BB*BB*BB*B***BB**BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "WBBBB*BB*BBB*BBB*B*BBBB*BBB*BB*B****BB*BB*BB*B*BB*B*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "WBBBB*BB***B*BBB*B*BBBB***B*BB*B*BB*BB*BBB**BB*BB*B***BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "WBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "WBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "WBB****************************************************************************************************BB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*                                                                                                  WBB*",
    "WBB*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB*",
    "WBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "WBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*",
    "W*********************************************************************************************************"
    
};


char degMode[15*2][19] = 
{
    // C
    " ***      ******* ",
    "** **    **BBB***B",
    "** **B  **BB   **B",
    "** **B  **B    **B",
    "** **B **BB     BB",
    "** **B **B        ",
    "** **B **B        ",
    " ***BB **B        ",
    "  BBB  **B        ",
    "       **B        ",
    "       **B     ** ",
    "        **     **B",
    "        ***   **BB",
    "         B*****BB ",
    "           BBBBB  ",

    // F
    " ***   *********  ",
    "** **   **BBBB**B ",
    "** **B  **B    ** ",
    "** **B  **B     BB",
    "** **B  **B  **   ",
    "** **B  **B  **B  ",
    "** **B  *******B  ",
    " ***BB  **BBB**B  ",
    "  BBB   **B  **B  ",
    "        **B   BB  ",
    "        **B       ",
    "        **B       ",
    "        **B       ",
    "       ****       ",
    "        BBBB      "
};

char numberFont[FONTCOUNT*FONTHEIGHT][FONTWIDTH] =
{
    //  0
    "     *****      ",
    "    ***BB**     ",
    "   ***BB ***    ",
    "  ***BB   ***   ",
    "  ***B    ***B  ",
    "  ***B     **B  ",
    " ***BB     ***  ",
    " ***B      ***B ",
    " ***B      ***B ",
    " ***B      ***B ",
    " ***B      ***B ",
    " ***B      ***B ",
    " ***B      ***B ",
    " ***B      ***B ",
    " ***B      ***B ",
    " ***B      ***B ",
    "  ***      **BB ",
    "  ***B    ***B  ",
    "  ***B    ***BB ",
    "   ***   ***BB  ",
    "    ***   **BB  ",
    "     *****BB    ",
    "      BBBBB     ",

    // 1
    "       **       ",
    "      ***B      ",
    "  *******B      ",
    "   BBB***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "      ***B      ",
    "     *****      ",
    "  ***********   ",
    "   BBBBBBBBBBB  ",

    // 2
    "    *******     ",
    "   **BBBB****   ",
    "  **BB    ***B  ",
    " **BB      ***  ",
    " **B       ***B ",
    " ***       ***B ",
    " ***B      ***B ",
    "  BBB      ***B ",
    "          ***BB ",
    "          ***B  ",
    "         ***BB  ",
    "        ***BB   ",
    "       ***BB    ",
    "      ***BB     ",
    "     ***BB      ",
    "     **BB       ",
    "    **BB    **  ",
    "   **BB     **B ",
    "  **BB      **B ",
    " **BB      ***B ",
    " ************BB ",
    " ************B  ",
    "  BBBBBBBBBBBB  ",

    // 3
    "    ******      ",
    "  ***BBB***     ",
    " ***BB   ***    ",
    " ***B     ***   ",
    " ***B     ***B  ",
    " ***B     ***B  ",
    "  BBB     ***B  ",
    "          ***B  ",
    "         ***BB  ",
    "        ***BB   ",
    "     *****BB    ",
    "      BB****    ",
    "         B***   ",
    "           **B  ",
    "           ***  ",
    "           ***B ",
    " ***       ***B ",
    " ***B      ***B ",
    " ***B      **BB ",
    " ***B     ***B  ",
    "  ***    ***BB  ",
    "   B******BBB   ",
    "     BBBBBB     ",

    // 4
    "        ***     ",
    "        ***B    ",
    "       ****B    ",
    "       ****B    ",
    "      *****B    ",
    "      *****B    ",  
    "     **B***B    ",
    "    **BB***B    ",
    "    **B ***B    ",
    "   **BB ***B    ",
    "   **B  ***B    ",
    "  **BB  ***B    ",
    " ***B   ***B    ",
    " **BB   ***B    ",
    "**BB    ***B    ",
    "**************  ",
    " BBBBBBB***BBBB ",
    "        ***B    ",
    "        ***B    ",
    "        ***B    ",
    "        ***B    ",
    "     *********  ",
    "      BBBBBBBBB ",

    //5
    "   ***********  ",
    "   ***********B ",
    "  **BBBBBBBBBBB ",
    "  **B           ",
    "  **B           ",
    "  **B           ",
    "  **B           ",
    "  **B           ",
    "  **B******     ",
    "  ****BBB***    ",
    "  ***BB   ***   ",
    "  **BB     **B  ",
    "   BB      ***  ",
    "           ***B ",
    "           ***B ",
    "           ***B ",
    " ***       ***B ",
    " ***B      ***B ",
    " **BB     ***BB ",
    " **B      ***B  ",
    "  ***    ***BB  ",
    "   B******BBB   ",
    "     BBBBBB     ",

    // 6
    "      *****     ",
    "    ***BBB***   ",
    "   ***BB  ***B  ",
    "   **BB   ***B  ",
    "  ***B     BBB  ",
    "  **BB          ",
    "  **B           ",
    " ***B           ",
    " ***B******     ",
    " ******BB***    ",
    " ****BBB  ***   ",
    " ****B     **B  ",
    " ***BB     ***  ",
    " ***B      ***B ",
    " ***B      ***B ",
    " ***B      ***B ",
    " ***B      ***B ",
    "  ***      ***B ",
    "  ***B     **BB ",
    "   ***    ***B  ",
    "   ****  ***BB  ",
    "    B******BB   ",
    "      BBBBBB    ",

    // 7
    "  ************  ",
    "  ************B ",
    "  **BBBBBBB**BB ",
    " ***B     **BB  ",
    " **BB     **B   ",
    " **B     **BB   ",
    "  BB     **B    ",
    "        **BB    ",
    "        **B     ",
    "        **B     ",
    "       **BB     ",
    "       **B      ",
    "      **BB      ",
    "      **B       ",
    "      **B       ",
    "      **B       ",
    "     ***B       ",
    "     ***B       ",
    "     ***B       ",
    "     ***B       ",
    "     ***B       ",
    "     ***B       ",
    "     ***B       ",
    "      BBB       ",

    // 8
    "    *******     ",
    "   ***BBB***    ",
    "  ***BB   ***   ",
    " ***BB     ***  ",
    " ***B      ***B ",
    " ***B      ***B ",
    " ****      ***B ",
    " ****B     **BB ",
    "  *****   ***B  ",
    "   ***** **BBB  ",
    "    ******BB    ",
    "  ***BB*****    ",
    " ***BB  *****   ",
    " ***B    ****B  ",
    "***BB     ****  ",
    "***B       ***B ",
    "***B       ***B ",
    "***B       ***B ",
    "***B       ***B ",
    " ***      ***BB ",
    "  ***    ***BB  ",
    "   B******BBB   ",
    "     BBBBBB     ",

    // 9
    "    ******      ",
    "  ***BBBB**     ",
    " ***BB    **    ",
    " ***B     ***   ",
    "***BB      **B  ",
    "***B       ***  ",
    "***B       ***B ",
    "***B       ***B ",
    "***B       ***B ",
    "***B       ***B ",
    "****      ****B ",
    " ***B    *****B ",
    "   ******BB***B ",
    "    BBBBBB ***B ",
    "          ***BB ",
    "          ***B  ",
    "          **BB  ",
    " ***     ***B   ",
    " ***B   ***BB   ",
    " ***B  ***BB    ",
    "  B******BB     ",
    "    BBBBBB      ",

    // -
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "     ********   ",
    "     ********B  ",
    "      BBBBBBBB  ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                "

};